fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        exclude: (.circleci/config.yml|.*__testdata__.*)
      - id: detect-private-key
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-xml
      - id: fix-byte-order-marker
      - id: destroyed-symlinks

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: circleci-config-validate
      - id: shellcheck
